const hiddenPathTours = [
  {
    id: "fansipan",
    name: "Tour leo nui Fansipan 2N1D xuat phat tu Ha Noi",
    displayName: "Tour leo núi Fansipan 2N1D (Xuất phát từ Hà Nội)",
    location: "Lào Cai",
    province: "lao-cai",
    altitude: "3143m",
    altitudeNum: 3143,
    duration: "2N1Đ",
    durationNum: 2,
    difficulty: "Trung bình khá",
    difficultyLevel: 3,
    price: 3500000,
    image: "img/tours/Fansipan.png",
    description: "Hành trình chạm nóc nhà Đông Dương, phù hợp với người đã có nền tảng thể lực tốt và muốn thử sức với biểu tượng núi cao Việt Nam.",
    rating: 4.9,
    reviewCount: 28,
    tags: ["featured"],
  },
  {
    id: "khang-su-van",
    name: "Tour leo nui Khang Su Van xuat phat tu Ha Noi",
    displayName: "Tour leo núi Khang Su Văn (Xuất phát từ Hà Nội)",
    location: "Lai Châu",
    province: "lai-chau",
    altitude: "3012m",
    altitudeNum: 3012,
    duration: "3N2Đ",
    durationNum: 3,
    difficulty: "Thách thức",
    difficultyLevel: 4,
    price: 4900000,
    image: "img/tours/khang su van.png",
    description: "Cung trekking hoang sơ vùng biên giới Phong Thổ, nổi bật với rừng rêu, rừng trúc và cột mốc 79 giữa biển mây.",
    rating: 4.9,
    reviewCount: 19,
    tags: ["featured"],
  },
  {
    id: "ky-quan-san",
    name: "Tour leo nui Ky Quan San Bach Moc Luong Tu xuat phat tu Ha Noi",
    displayName: "Tour leo núi Ky Quan San - Bạch Mộc Lương Tử (Xuất phát từ Hà Nội)",
    location: "Lào Cai",
    province: "lao-cai",
    altitude: "3046m",
    altitudeNum: 3046,
    duration: "3N2Đ",
    durationNum: 3,
    difficulty: "Thách thức",
    difficultyLevel: 4,
    price: 4900000,
    image: "img/tours/Ky quan san.png",
    description: "Một trong những cung săn mây đẹp nhất Tây Bắc, đi qua rừng trúc, sống núi và các điểm ngắm bình minh rộng mở.",
    rating: 4.9,
    reviewCount: 31,
    tags: ["featured"],
  },
  {
    id: "lao-than",
    name: "Tour leo nui Lao Than xuat phat tu Ha Noi",
    displayName: "Tour leo núi Lảo Thẩn (Xuất phát từ Hà Nội)",
    location: "Lào Cai",
    province: "lao-cai",
    altitude: "2860m",
    altitudeNum: 2860,
    duration: "2N1Đ",
    durationNum: 2,
    difficulty: "Trung bình",
    difficultyLevel: 2,
    price: 3800000,
    image: "img/tours/lao than.png",
    description: "Cung trekking vừa sức tại Y Tý, nổi tiếng với hoàng hôn, bình minh và những khoảng trời mây thoáng rộng.",
    rating: 4.8,
    reviewCount: 24,
    tags: ["featured"],
  },
  {
    id: "nam-kang-ho-tao",
    name: "Tour leo nui Nam Kang Ho Tao xuat phat tu Ha Noi",
    displayName: "Tour leo núi Nam Kang Ho Tao (Xuất phát từ Hà Nội)",
    location: "Lai Châu",
    province: "lai-chau",
    altitude: "2881m",
    altitudeNum: 2881,
    duration: "3N2Đ",
    durationNum: 3,
    difficulty: "Thách thức",
    difficultyLevel: 5,
    price: 4900000,
    image: "img/tours/Nam kang ho tao.png",
    description: "Cung leo nhiều thử thách với suối, thác, rừng rậm và địa hình kỹ thuật dành cho người có kinh nghiệm trekking.",
    rating: 4.9,
    reviewCount: 16,
    tags: ["featured"],
  },
  {
    id: "ngu-chi-son",
    name: "Tour leo nui Ngu Chi Son xuat phat tu Ha Noi",
    displayName: "Tour leo núi Ngũ Chỉ Sơn (Xuất phát từ Hà Nội)",
    location: "Lào Cai",
    province: "lao-cai",
    altitude: "2858m",
    altitudeNum: 2858,
    duration: "3N2Đ",
    durationNum: 3,
    difficulty: "Thách thức",
    difficultyLevel: 4,
    price: 2500000,
    image: "img/tours/ngu chi son.png",
    description: "Dãy núi năm ngón tay kỳ vĩ, tuyến đi nhiều đoạn dốc và rừng nguyên sinh với tầm nhìn rộng về thung lũng Sa Pa.",
    rating: 4.8,
    reviewCount: 18,
    tags: ["featured"],
  },
  {
    id: "nhiu-co-san",
    name: "Tour leo nui Nhiu Co San xuat phat tu Ha Noi",
    displayName: "Tour leo núi Nhìu Cồ San (Xuất phát từ Hà Nội)",
    location: "Lào Cai",
    province: "lao-cai",
    altitude: "2965m",
    altitudeNum: 2965,
    duration: "2N1Đ",
    durationNum: 2,
    difficulty: "Thách thức",
    difficultyLevel: 4,
    price: 4150000,
    image: "img/tours/nhiu co san.png",
    description: "Cung núi cao ở Bát Xát với rừng rậm, suối đá và những lớp mây dày đặc đặc trưng vùng biên viễn.",
    rating: 4.9,
    reviewCount: 22,
    tags: ["featured"],
  },
  {
    id: "phu-sa-phin",
    name: "Tour leo nui Phu Sa Phin xuat phat tu Ha Noi",
    displayName: "Tour leo núi Phu Sa Phìn (Xuất phát từ Hà Nội)",
    location: "Yên Bái",
    province: "yen-bai",
    altitude: "2868m",
    altitudeNum: 2868,
    duration: "2N1Đ",
    durationNum: 2,
    difficulty: "Nâng cao",
    difficultyLevel: 3,
    price: 4500000,
    image: "img/tours/Phu sa phin.png",
    description: "Cung Ta Xùa hướng Hang Chú với sống núi nguyên sơ, rừng già và những lớp mây phủ dày trên dãy Hoàng Liên.",
    rating: 4.8,
    reviewCount: 20,
    tags: ["featured"],
  },
  {
    id: "pu-ta-leng",
    name: "Tour leo nui Pu Ta Leng xuat phat tu Ha Noi",
    displayName: "Tour leo núi Pu Ta Leng (Xuất phát từ Hà Nội)",
    location: "Lai Châu",
    province: "lai-chau",
    altitude: "3049m",
    altitudeNum: 3049,
    duration: "3N2Đ",
    durationNum: 3,
    difficulty: "Thách thức",
    difficultyLevel: 4,
    price: 4850000,
    image: "img/tours/putaleng.png",
    description: "Hành trình xuyên rừng nguyên sinh, rêu phong và suối đá để chinh phục một trong những đỉnh cao nhất Việt Nam.",
    rating: 4.9,
    reviewCount: 34,
    tags: ["featured"],
  },
  {
    id: "ta-lien-son",
    name: "Tour leo nui Ta Lien Son xuat phat tu Ha Noi",
    displayName: "Tour leo núi Tả Liên Sơn (Xuất phát từ Hà Nội)",
    location: "Lai Châu",
    province: "lai-chau",
    altitude: "2996m",
    altitudeNum: 2996,
    duration: "2N1Đ",
    durationNum: 2,
    difficulty: "Nâng cao",
    difficultyLevel: 3,
    price: 4100000,
    image: "img/tours/ta lien son.png",
    description: "Cung trekking qua rừng cổ thụ xanh dày, đỉnh nhìn xuống thành phố Lai Châu và những dải núi trập trùng.",
    rating: 4.8,
    reviewCount: 21,
    tags: ["featured"],
  },
];

window.hiddenPathTours = hiddenPathTours;
